apiVersion: v1
kind: Service
metadata:
  name: {{ include "test2.fullname" . }}
  labels:
    {{- include "test2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30002
      protocol: TCP
      name: http
  selector:
    {{- include "test2.selectorLabels" . | nindent 4 }}
