apiVersion: v1
kind: Service
metadata:
  name: {{ include "third.fullname" . }}
  labels:
    {{- include "third.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: 30003
      protocol: TCP
      name: http
  selector:
    {{- include "third.selectorLabels" . | nindent 4 }}
